In [1]:
import numpy as np

In [2]:
arr= np.arange(start=2,stop=50,step=3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [6]:
input1_string=input("enter the elements of list1")
list1=input1_string.split()
print()
input2_string=input("enter the elements of list 2")
list2=input2_string.split()
print()
arr1=np.array(list1)
print()
print(arr1)
arr2=np.array(list2)
print()
print(arr2)
arr=np.concatenate((arr1,arr2))
print()
print(arr)
print()
sarray=np.sort(arr1)
sarray1=np.sort(arr2)
print(sarray)
print(sarray1)



enter the elements of list18,9,3,2,1

enter the elements of list 26,9,7,3,2


['8,9,3,2,1']

['6,9,7,3,2']

['8,9,3,2,1' '6,9,7,3,2']

['8,9,3,2,1']
['6,9,7,3,2']


In [8]:
a_1d = np.arange(3)
print(a_1d)
print(a_1d.ndim)
print(a_1d.size)

[0 1 2]
1
3


In [9]:
a_2d = np.arange(12).reshape((3, 4))
print(a_2d)
print(a_2d.ndim)
print(a_2d.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
12


In [10]:
gfg = np.array([1, 2]) 
print(gfg.shape) 
  
gfg = np.expand_dims(gfg, axis = 0) 
print(gfg.shape) 

(2,)
(1, 2)


In [11]:
arr = np.arange(5*5).reshape(5, 5) 
print(arr.shape) 
  
# promoting 2D array to a 5D array 
# arr[None, ..., None, None] 
arr_5D = arr[np.newaxis, ..., np.newaxis, np.newaxis] 
  
print(arr_5D.shape)

(5, 5)
(1, 5, 5, 1, 1)


In [12]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [13]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [14]:
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
  
# taking an input list 
l1 = [] 
  
# taking an counter 
count = 0
  
# travesing the array 
for item in input_list: 
    if item not in l1: 
        count += 1
        l1.append(item) 
  
# printing the output 
print("No of unique items are:", count) 

No of unique items are: 5
